//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTAInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallenTbl
    {
        public int challenNo { get; set; }
        public string name { get; set; }
        public string licenceNo { get; set; }
        public string platNo { get; set; }
        public decimal amount { get; set; }
    }
}
