//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTAInformationSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RTADataEntities : DbContext
    {
        public RTADataEntities()
            : base("name=RTADataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplyTbl> ApplyTbls { get; set; }
        public DbSet<ChallenTbl> ChallenTbls { get; set; }
        public DbSet<RegisterTbl> RegisterTbls { get; set; }
    }
}
